; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:espwroom32]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
build_flags = -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY -DLOGGING_REDEFINE_LOG_X
board_build.partitions = min_spiffs.csv
monitor_filters = colorize, esp32_exception_decoder
; monitor_port selected at upload
; upload_port selected at upload
monitor_speed = 115200
upload_speed = 115200
lib_deps = 
	bblanchon/ArduinoJson@6.21.3
	knolleary/PubSubClient@2.8.0
	https://github.com/esp32m/logging.git#ce0303f696171b359d0351dcfca2a125bf0b8b0b
